apiVersion: v1
kind: Service
metadata:
  name: parking-backend-service
  namespace: parking
spec:
  type: LoadBalancer
  selector:
    app: parking-backend
  ports:
  - port: 5000
    targetPort: 5000
